#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  OMNI-ICT Auto Trader — Setup Wizard
#  Run:  bash setup.sh
# ═══════════════════════════════════════════════════════════════

set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

say()  { echo -e "${CYAN}${BOLD}► $*${RESET}"; }
ok()   { echo -e "${GREEN}✓ $*${RESET}"; }
warn() { echo -e "${YELLOW}⚠ $*${RESET}"; }
err()  { echo -e "${RED}✗ $*${RESET}"; exit 1; }
ask()  { echo -e "${BOLD}$1${RESET}"; read -r REPLY; echo "$REPLY"; }

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║     OMNI-ICT Auto Trader  —  Setup       ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${RESET}"
echo ""

# ── Step 1: Check dependencies ──────────────────────────────
say "Checking dependencies..."

if command -v docker &>/dev/null && docker compose version &>/dev/null 2>&1; then
    ok "Docker + Docker Compose found"
    USE_DOCKER=true
elif command -v python3 &>/dev/null; then
    ok "Python3 found (no Docker — will run directly)"
    USE_DOCKER=false
else
    err "Neither Docker nor Python3 found. Install Docker Desktop from https://docker.com"
fi

# ── Step 2: License key ─────────────────────────────────────
echo ""
say "License Key"
echo "Your license key was emailed to you after purchase."
echo "It looks like: OMNI-XXXX-XXXX-XXXX"
echo "If you don't have one, visit: https://omni-ict.com"
echo ""
LICENSE_KEY=$(ask "Paste your license key:")
if [[ -z "$LICENSE_KEY" ]]; then
    err "License key is required."
fi

# ── Step 3: Telegram bot token ──────────────────────────────
echo ""
say "Telegram Bot Token"
echo "1. Open Telegram and message @BotFather"
echo "2. Send: /newbot"
echo "3. Follow the prompts (choose any name/username)"
echo "4. Copy the token it gives you (looks like: 123456:ABC-DEF...)"
echo ""
TG_TOKEN=$(ask "Paste your Telegram bot token:")
if [[ -z "$TG_TOKEN" ]]; then
    err "Telegram token is required."
fi

# ── Step 4: MT5 account ─────────────────────────────────────
echo ""
say "MT5 Account"
echo "Open your MT5 account through our recommended broker:"
echo ""
echo -e "  ${BOLD}${GREEN}https://www.midasfx.com/?ib=1128101${RESET}"
echo ""
echo "After opening an account, you'll receive:"
echo "  • Account number (login)"
echo "  • Password"
echo "  • Server name (e.g. MetaQuotes-Demo)"
echo ""
MT5_LOGIN=$(ask "MT5 account number (login):")
MT5_PASS=$(ask "MT5 password:")
MT5_SERVER=$(ask "MT5 server (e.g. MetaQuotes-Demo):")

# ── Step 5: MT5 data directory ──────────────────────────────
echo ""
say "MT5 Data Directory"
echo "This is where MT5 writes its data files."
echo "Default locations:"
echo "  Windows: C:\\Users\\YourName\\AppData\\Roaming\\MetaQuotes\\Terminal\\Common\\Files"
echo "  Linux:   /home/user/.wine/drive_c/users/user/AppData/Roaming/MetaQuotes/Terminal/Common/Files"
echo "  macOS:   /Users/YourName/Library/Application Support/net.metaquotes.wine.metatrader5/..."
echo ""
echo "Press Enter to use default (/tmp/mt5data) or paste your path:"
read -r MT5_DIR
MT5_DIR="${MT5_DIR:-/tmp/mt5data}"

# ── Step 6: Risk mode ───────────────────────────────────────
echo ""
say "Risk Mode"
echo "  1) LOW          — 0.5% risk per trade (safest)"
echo "  2) MODERATE     — 1.0% risk per trade (recommended for new users)"
echo "  3) HIGH         — 2.0% risk per trade (experienced traders only)"
echo ""
RISK_CHOICE=$(ask "Choose [1/2/3] (default: 2):")
case "$RISK_CHOICE" in
    1) RISK_MODE="LOW" ;;
    3) RISK_MODE="HIGH" ;;
    *) RISK_MODE="MODERATE" ;;
esac

# ── Step 7: Anthropic API key ───────────────────────────────
echo ""
say "Anthropic API Key (optional — for AI market analysis)"
echo "Get yours free at: https://console.anthropic.com"
echo "Press Enter to skip for now:"
read -r ANTHROPIC_KEY
ANTHROPIC_KEY="${ANTHROPIC_KEY:-sk-ant-placeholder}"

# ── Write .env ──────────────────────────────────────────────
echo ""
say "Writing configuration..."

cat > .env <<EOF
# Generated by setup.sh on $(date)
OMNI_LICENSE_KEY=${LICENSE_KEY}
OMNI_TELEGRAM_TOKEN=${TG_TOKEN}

MT5_LOGIN=${MT5_LOGIN}
MT5_PASSWORD=${MT5_PASS}
MT5_SERVER=${MT5_SERVER}

OMNI_RISK_MODE=${RISK_MODE}
OMNI_FREQ_MODE=NORMAL
OMNI_PAPER_MODE=true

ANTHROPIC_API_KEY=${ANTHROPIC_KEY}

MT5_DATA_DIR=${MT5_DIR}
EOF

ok ".env written"

# ── Write config.json from example ──────────────────────────
if [[ ! -f config.json ]]; then
    if [[ -f config.example.json ]]; then
        # Update data_path with the provided MT5 dir
        python3 -c "
import json, sys
cfg = json.load(open('config.example.json'))
mt5_dir = '${MT5_DIR}'
for acc in cfg.get('accounts', []):
    if mt5_dir != '/tmp/mt5data':
        acc['data_path'] = mt5_dir + '/omni_data.json'
        acc['cmd_path']  = mt5_dir + '/omni_cmd.txt'
    acc['mt5_login']    = '${MT5_LOGIN}'
    acc['mt5_password'] = '${MT5_PASS}'
    acc['mt5_server']   = '${MT5_SERVER}'
json.dump(cfg, open('config.json','w'), indent=2)
print('config.json written')
" 2>/dev/null || cp config.example.json config.json
        ok "config.json written"
    fi
fi

# ── Start the bot ────────────────────────────────────────────
echo ""
say "Starting OMNI-ICT..."
echo ""

if [[ "$USE_DOCKER" == "true" ]]; then
    docker compose up -d
    echo ""
    ok "Docker containers started!"
    echo ""
    echo -e "${BOLD}Next steps:${RESET}"
    echo "  1. Watch logs:     docker compose logs -f"
    echo "  2. Open Telegram → message your bot → send /start"
    echo "  3. Send /dashboard to see your live account"
    echo ""
    echo -e "${BOLD}MT5 setup (important!):${RESET}"
    echo "  1. Open MetaTrader 5"
    echo "  2. Attach the OMNI EA to a chart (included in the /mql5 folder)"
    echo "  3. Enable AutoTrading in MT5"
    echo "  4. The bot will detect the connection automatically"
    echo ""
    echo -e "${YELLOW}⚠  PAPER MODE IS ON — no real money at risk until you run /set paper off${RESET}"
else
    # Direct Python run
    mkdir -p logs shared pine
    if [[ ! -d venv ]]; then
        python3 -m venv venv
        venv/bin/pip install -q -r requirements.txt
    fi
    ok "Dependencies installed"
    echo ""
    echo -e "${BOLD}Starting watchdog...${RESET}"
    nohup venv/bin/python python/watchdog.py > logs/launchagent.out.log 2>&1 &
    echo $! > logs/watchdog.pid
    echo ""
    ok "OMNI-ICT started (PID $(cat logs/watchdog.pid))"
    echo ""
    echo -e "${BOLD}Next steps:${RESET}"
    echo "  1. Open Telegram → message your bot → send /start"
    echo "  2. Send /dashboard to see your live account"
    echo "  3. Check logs: tail -f logs/telegram_bot.log"
    echo ""
    echo -e "${YELLOW}⚠  PAPER MODE IS ON — no real money at risk until you run /set paper off${RESET}"
fi

echo ""
echo -e "${GREEN}${BOLD}Setup complete! Welcome to OMNI-ICT. 🚀${RESET}"
echo ""
