"""
pine_codegen.py — Generates a TradingView Pine v5 overlay from OMNI signals.

Input: list[Signal] (from signal_writers.py).
Output: a complete, copy-paste-able Pine v5 script string showing:
    · horizontal lines at entry / SL / TP
    · labels with direction, entry_type, confidence
    · background tint per direction

Design: pure function. Caller decides where to write the .pine file.
"""

from __future__ import annotations

from typing import Iterable
from signal_writers import Signal


PINE_HEADER = """// @version=5
// Auto-generated by omni-ict pine_codegen.py. Do not edit by hand.
indicator("OMNI Signal Overlay", overlay=true, max_lines_count=500, max_labels_count=500)

// ── Config ──────────────────────────────────────────────
bullCol = input.color(color.new(color.teal,    0),  "Bull color")
bearCol = input.color(color.new(color.red,     0),  "Bear color")
slCol   = input.color(color.new(color.orange,  0),  "SL color")
tpCol   = input.color(color.new(color.green,   0),  "TP color")
lineW   = input.int(2, "Line width", minval=1, maxval=5)
"""


def _esc(s: str) -> str:
    """Escape a string for Pine single-quoted usage (no newlines, simple)."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").replace("\r", "")


def _emit_signal_block(idx: int, sig: Signal) -> str:
    """Emit one self-contained block of Pine statements for a given signal."""
    if sig.direction not in ("BULL", "BEAR") or sig.entry_price is None:
        # Non-actionable — emit nothing
        return f"// [{idx}] skipped: {_esc(sig.symbol)} {sig.direction} {sig.entry_type}\n"

    col_var = "bullCol" if sig.direction == "BULL" else "bearCol"
    label_str = f"{sig.symbol} {sig.direction} {sig.entry_type} ({sig.confidence:.2f})"
    label_str = _esc(label_str)
    # Pine `time` variable isn't useful for a past signal when just recreating;
    # we use `bar_index` for x-anchor. Draw on the current/last bar so user sees
    # the level on their chart. (Production alt: use timestamp and map to bar.)
    entry = sig.entry_price

    lines = [
        f"// [{idx}] {_esc(sig.id)}\n",
        f"if barstate.islast\n",
        f"    line.new(bar_index - 50, {entry}, bar_index, {entry}, "
        f"color={col_var}, width=lineW)\n",
        f"    label.new(bar_index, {entry}, \"{label_str}\", "
        f"color={col_var}, textcolor=color.white, style=label.style_label_left, size=size.small)\n",
    ]
    # Only draw SL/TP lines when a valid non-zero price is available
    if sig.sl is not None and sig.sl != 0.0:
        lines.insert(3, f"    line.new(bar_index - 50, {sig.sl}, bar_index, {sig.sl}, "
                        f"color=slCol, style=line.style_dashed, width=1)\n")
    if sig.tp is not None and sig.tp != 0.0:
        lines.insert(-1, f"    line.new(bar_index - 50, {sig.tp}, bar_index, {sig.tp}, "
                         f"color=tpCol, style=line.style_dashed, width=1)\n")
    return "".join(lines)


def generate_pine(signals: Iterable[Signal]) -> str:
    """Return a complete Pine v5 script drawing every signal."""
    parts = [PINE_HEADER, "\n// ── Signals ───────────────────────────────\n"]
    count = 0
    for i, sig in enumerate(signals):
        parts.append(_emit_signal_block(i, sig))
        count += 1
    if count == 0:
        parts.append("// (no signals this cycle)\n")
    return "".join(parts)


def write_pine(signals: Iterable[Signal], out_path: str) -> None:
    """Pure-write helper. Caller owns the path."""
    import os
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    tmp = out_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(generate_pine(signals))
    os.replace(tmp, out_path)


# ──────────────────────────────────────────────────────────────────────────────
# Self-test
# ──────────────────────────────────────────────────────────────────────────────

def _self_test() -> None:
    from signal_writers import Signal
    sigs = [
        Signal(id="t-1", ts="2026-04-16T12:00:00+00:00",
               symbol="EURUSD", timeframe="M5", direction="BULL",
               entry_type="ob_mitigation",
               entry_price=1.1234, sl=1.1200, tp=1.1300,
               confidence=0.82, reasons=["HTF BULL", "LTF OB"],
               scale_action="HOLD", scale_mult=1.0, htf_bias="BULL"),
        Signal(id="t-2", ts="2026-04-16T12:00:00+00:00",
               symbol="GBPUSD", timeframe="M5", direction="NEUTRAL",
               entry_type="none",
               entry_price=None, sl=None, tp=None,
               confidence=0.10, reasons=["no trigger"], htf_bias="NEUTRAL"),
    ]
    script = generate_pine(sigs)
    assert "indicator(" in script
    assert "EURUSD BULL" in script
    assert "skipped: GBPUSD" in script
    print("[OK] pine_codegen produced", len(script), "chars")
    print("---- first 400 chars ----")
    print(script[:400])


if __name__ == "__main__":
    _self_test()
